### ISSUE TITLE
[TODO] C#, 유니티 관련 문서 추가 예정

### ISSUE THREAD

**Issue by HUSK-321** [Romanticism-GameDeveloper/GameDeveloper-Client-Interview#2]
## List

- [x] Awake, Start, Update, LateUpdate, FixedUpdate 들의 차이
- [x] readonly vs const
- [x] List vs Dictionary
- [x] this
